version: 2
jobs:
  build:
    working_directory: ~/gql-dg-tmp
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
      - image: circleci/python:3.8.1
        environment:
                DATABASE_URL: postgresql://happuser:newypass@localhost/bestwishesdb?sslmode=disable
      - image: circleci/postgres:12.1
        environment:
          POSTGRES_USER: happuser
          POSTGRES_DB: bestwishesdb
      - image: circleci/node:buster

    steps:
      - checkout  # Get the latest clone of the repo in CI.
      - run:
          name: Set-up test_results directory and set-up permissions
          command: |
            mkdir -p $TEST_RESULTS
            sudo chown -R circleci:circleci /usr/local/bin
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v12.14.1/node-v12.14.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.14.1-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Test npm install
          command: |
            #fix -g install permission
            #useradd -m circleci
            #npm set unsafe-perm true
            npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
            npm install -g --loglevel=warn npx webpack webpack-cli jest
            #npm install -g npx webpack webpack-cli jest npm
            node --version
            npm --version
      - run:
          name: Update apt source list for Postgres
          command: |
            #wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            #sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/PostgreSQL.list'
            sudo apt update
            sudo apt-get install -y postgresql postgresql-contrib
            #sudo apt-get update && sudo apt-get install -y postgresql-client-12
            sudo apt-get update && sudo apt-get install -y --no-install-recommends apt-utils
            sudo apt-get update && sudo apt-get upgrade -y 
            #sudo apt-get update && sudo apt-get install -y postgresql-12 postgresql-contrib-12 python-psycopg2 
            sudo service postgresql start
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Install requirements
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            ./run_test.sh
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
